import { mysqlTable, serial, varchar, double, enumType, tinyint, date } from 'drizzle-orm/mysql-core';

export const applicationsettings = mysqlTable('applicationsettings', {
  id: serial('id').primaryKey(),
  SYS_LANG: varchar('SYS_LANG', { length: 10 }).notNull().default('en'),
  MAX_OBTAINABLE_FDADVANCE_LOAN_PERCENTAGE: varchar('MAX_OBTAINABLE_FDADVANCE_LOAN_PERCENTAGE', { length: 5 }).default('0.00').comment('Max obtainable FD Advance Loan percentage'),
  INTEREST_INCREEMENT_FOR_FDADVANCE_LOAN: varchar('INTEREST_INCREEMENT_FOR_FDADVANCE_LOAN', { length: 3 }).default('0').comment('Interest Increasing amount for FD Advance loans'),
  PASS_CARD_PAGE_RENEW_MAX_NUMBER: varchar('PASS_CARD_PAGE_RENEW_MAX_NUMBER', { length: 2 }).default('0'),
  PASS_BOOK_PAGE_GUTTER_START_NUMBER: varchar('PASS_BOOK_PAGE_GUTTER_START_NUMBER', { length: 2 }).default('0'),
  PASS_BOOK_PAGE_GUTTER_END_NUMBER: varchar('PASS_BOOK_PAGE_GUTTER_END_NUMBER', { length: 2 }).default('0'),
  PASS_BOOK_PAGE_RENEW_MAX_NUMBER: varchar('PASS_BOOK_PAGE_RENEW_MAX_NUMBER', { length: 2 }).default('0'),
  SMS_1ST_PASTDUE_REMINDER_DAYS: double('SMS_1ST_PASTDUE_REMINDER_DAYS').default(null),
  SMS_2ND_PASTDUE_REMINDER_DAYS: double('SMS_2ND_PASTDUE_REMINDER_DAYS').default(null),
  SMS_3RD_PASTDUE_REMINDER_DAYS: double('SMS_3RD_PASTDUE_REMINDER_DAYS').default(null),
  SMS_4TH_PASTDUE_REMINDER_DAYS: double('SMS_4TH_PASTDUE_REMINDER_DAYS').default(null),
  SMS_5TH_PASTDUE_REMINDER_DAYS: double('SMS_5TH_PASTDUE_REMINDER_DAYS').default(null),
  LETTER_OF_DEMAND_DAYS: double('LETTER_OF_DEMAND_DAYS').default(null),
  PASTDUE_LETTER_TYPE: double('PASTDUE_LETTER_TYPE').default('1').comment('1 - By Pastdue Installment, 2 - By Pastdue Days'),
  LET_1ST_PASTDUE_REMINDER_DAYS: double('LET_1ST_PASTDUE_REMINDER_DAYS').default(null),
  LET_2ND_PASTDUE_REMINDER_DAYS: double('LET_2ND_PASTDUE_REMINDER_DAYS').default(null),
  LET_3RD_PASTDUE_REMINDER_DAYS: double('LET_3RD_PASTDUE_REMINDER_DAYS').default(null),
  LET_4TH_PASTDUE_REMINDER_DAYS: double('LET_4TH_PASTDUE_REMINDER_DAYS').default(null),
  LET_5TH_PASTDUE_REMINDER_DAYS: double('LET_5TH_PASTDUE_REMINDER_DAYS').default(null),
  LET_LETTER_OF_DEMAND_DAYS: double('LET_LETTER_OF_DEMAND_DAYS').default(null),
  LET_1ST_PAWN_REMINDER_DAYS: double('LET_1ST_PAWN_REMINDER_DAYS').default('351'),
  LET_2ND_PAWN_REMINDER_DAYS: double('LET_2ND_PAWN_REMINDER_DAYS').default('365'),
  LET_3RD_PAWN_REMINDER_DAYS: double('LET_3RD_PAWN_REMINDER_DAYS').default('379'),
  LET_AUCTION_LETTER_DAYS: double('LET_AUCTION_LETTER_DAYS').default('393'),
  LET_1ST_PASTDUE_REMINDER_INS: double('LET_1ST_PASTDUE_REMINDER_INS').default(null),
  LET_2ND_PASTDUE_REMINDER_INS: double('LET_2ND_PASTDUE_REMINDER_INS').default(null),
  LET_3RD_PASTDUE_REMINDER_INS: double('LET_3RD_PASTDUE_REMINDER_INS').default(null),
  LET_4TH_PASTDUE_REMINDER_INS: double('LET_4TH_PASTDUE_REMINDER_INS').default(null),
  LET_5TH_PASTDUE_REMINDER_INS: double('LET_5TH_PASTDUE_REMINDER_INS').default(null),
  LET_LETTER_OF_DEMAND_INS: double('LET_LETTER_OF_DEMAND_INS').default(null),
  SMS_TOTAL_PASTDUE_LETTERS: enumType('SMS_TOTAL_PASTDUE_LETTERS', ['1', '2', '3', '4', '5']).default(null),
  LET_TOTAL_PASTDUE_LETTER: enumType('LET_TOTAL_PASTDUE_LETTER', ['1', '2', '3', '4', '5']).default(null),
  LET_TOTAL_PAWN_LETTER: enumType('LET_TOTAL_PAWN_LETTER', ['1', '2', '3', '4', '5']).default('4'),
  BATCH_DEPOSIT_UPDATE_SAME_ACCOUNT: tinyint('BATCH_DEPOSIT_UPDATE_SAME_ACCOUNT').default('1').comment('1 - Update Same Account 0 - Seperate enry for same account'),
  PAWNING_ISSUE_PERCENTAGE: double('PAWNING_ISSUE_PERCENTAGE').default('80'),
  PAWNING_AMOUNT_FOR_24K_GOLD: double('PAWNING_AMOUNT_FOR_24K_GOLD').default('0'),
  MARKET_VALUE_FOR_24K_GOLD: double('MARKET_VALUE_FOR_24K_GOLD').default('0'),
  EXTRA_INTEREST_INCREEMENT_FOR_FDADVANCE_LOAN: varchar('EXTRA_INTEREST_INCREEMENT_FOR_FDADVANCE_LOAN', { length: 4 }).default(null),
  LAST_YEAR_ENDED_DATE: date('LAST_YEAR_ENDED_DATE').default(null),
}, {
  charset: 'latin1',
});
