import { mysqlTable, varchar, int, date, datetime, mediumblob, decimal, enum as mysqlEnum } from 'drizzle-orm/mysql-core';

export const customerinformation = mysqlTable('customerinformation', {
  CustomerType: varchar('CustomerType', { length: 50 }),
  CustomerTitle: varchar('CustomerTitle', { length: 10 }),
  sCustomerTitle: varchar('sCustomerTitle', { length: 20 }),
  CustomerID: varchar('CustomerID', { length: 12 }).primaryKey(),
  loan_center_id: int('loan_center_id'),
  GroupCode: varchar('GroupCode', { length: 5 }),
  SubGroupCode: varchar('SubGroupCode', { length: 100 }),
  NameInInitials: varchar('NameInInitials', { length: 100 }),
  CustomerName: varchar('CustomerName', { length: 100 }),
  sCustomerName: varchar('sCustomerName', { length: 100 }),
  CustomerFullName: varchar('CustomerFullName', { length: 300 }),
  sCustomerFullName: varchar('sCustomerFullName', { length: 300 }),
  HomeNo: varchar('HomeNo', { length: 100 }),
  sHomeNo: varchar('sHomeNo', { length: 100 }),
  HomeStreet: varchar('HomeStreet', { length: 100 }),
  sHomeStreet: varchar('sHomeStreet', { length: 100 }),
  HomeTown: varchar('HomeTown', { length: 100 }),
  sHomeTown: varchar('sHomeTown', { length: 100 }),
  CustomerAddress: varchar('CustomerAddress', { length: 300 }).default('-'),
  sCustomerAddress: varchar('sCustomerAddress', { length: 300 }),
  HomeCountry: varchar('HomeCountry', { length: 40 }),
  BussinessName: varchar('BussinessName', { length: 100 }),
  BussinessLocationNo: varchar('BussinessLocationNo', { length: 40 }),
  BusinessStreet: varchar('BusinessStreet', { length: 40 }),
  BussinessTown: varchar('BussinessTown', { length: 40 }),
  BussinessAddress: varchar('BussinessAddress', { length: 200 }).default('-'),
  BirthDay: date('BirthDay'),
  NIC: varchar('NIC', { length: 20 }).default('-'),
  BeneficiaryNIC: varchar('BeneficiaryNIC', { length: 100 }),
  Sex: varchar('Sex', { length: 10 }),
  Occupation: varchar('Occupation', { length: 50 }).default('-'),
  PersonnalTelephoneNo: varchar('PersonnalTelephoneNo', { length: 15 }),
  PersonnalMobileNo: varchar('PersonnalMobileNo', { length: 25 }).default('-'),
  PersonnalEMail: varchar('PersonnalEMail', { length: 100 }).default('-'),
  HomeTelephoneNo: varchar('HomeTelephoneNo', { length: 15 }).default('-'),
  BusinessTelephoneNo: varchar('BusinessTelephoneNo', { length: 15 }).default('-'),
  BusinessMobileNo: varchar('BusinessMobileNo', { length: 15 }).default('-'),
  WebSite: varchar('WebSite', { length: 100 }).default('-'),
  District: varchar('District', { length: 50 }).default('-'),
  AGDivision: varchar('AGDivision', { length: 50 }).default('-'),
  GSDivisionName: varchar('GSDivisionName', { length: 50 }).default('-'),
  GSDivisionNo: varchar('GSDivisionNo', { length: 20 }).default('-'),
  Religion: varchar('Religion', { length: 50 }).default('-'),
  MaritalStatus: varchar('MaritalStatus', { length: 20 }),
  JoinedDate: date('JoinedDate'),
  AccountTransfereeName: varchar('AccountTransfereeName', { length: 250 }).default('-'),
  TransfereesRelationship: varchar('TransfereesRelationship', { length: 100 }).default('-'),
  MemberStatus: varchar('MemberStatus', { length: 10 }).default('-'),
  ImportantNote: varchar('ImportantNote', { length: 200 }).default('-'),
  smsRegistered: int('smsRegistered').default(0),
  smsLang: varchar('smsLang', { length: 6 }).default('EN'),
  smsPhone: varchar('smsPhone', { length: 15 }),
  smsPin: varchar('smsPin', { length: 6 }),
  fg_pr: mediumblob('fg_pr'),
  fg_pr1: mediumblob('fg_pr1'),
  currentCreditLimit: decimal('currentCreditLimit', { precision: 23, scale: 13 }),
  previousCreditLimit: decimal('previousCreditLimit', { precision: 23, scale: 13 }),
  creditStartDate: date('creditStartDate'),
  creditEndDate: date('creditEndDate'),
  ussdRegCode: varchar('ussdRegCode', { length: 6 }),
  ussdPassword: varchar('ussdPassword', { length: 4 }),
  ussdMobileHash: varchar('ussdMobileHash', { length: 200 }),
  ussdRegisteredOn: datetime('ussdRegisteredOn'),
  InstituteId: varchar('InstituteId', { length: 2 }),
  ReferenceNumber: varchar('ReferenceNumber', { length: 20 }).default('-'),
  Landmark: varchar('Landmark', { length: 255 }),
  Location: varchar('Location', { length: 150 }),
  username: varchar('username', { length: 100 }),
  password: varchar('password', { length: 100 }),
  locale: varchar('locale', { length: 10 }).default('EN'),
  ReceivableWelfareRegistrationFee: decimal('ReceivableWelfareRegistrationFee', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ReceivableRegistrationFee: decimal('ReceivableRegistrationFee', { precision: 23, scale: 13 }).default('0.0000000000000'),
  IsWHTAllowed: mysqlEnum('IsWHTAllowed', ['Y', 'N']).default('N'),
  device_user_name: varchar('device_user_name', { length: 15 }),
  FPEnrollID: varchar('FPEnrollID', { length: 255 }),
}, {
  charset: 'latin1',
});
