import { mysqlTable, varchar, enumType, mediumblob, int, double, date } from 'drizzle-orm/mysql-core';

export const instituteinformation = mysqlTable('instituteinformation', {
  InstituteID: varchar('InstituteID', { length: 4 }).primaryKey(),
  InstituteName: varchar('InstituteName', { length: 100 }),
  sInstituteName: varchar('sInstituteName', { length: 100 }).comment('In Secondary Language'),
  InstituteAddress: varchar('InstituteAddress', { length: 150 }),
  sInstituteAddress: varchar('sInstituteAddress', { length: 150 }),
  InstituteLocationNo: varchar('InstituteLocationNo', { length: 40 }),
  sInstituteLocationNo: varchar('sInstituteLocationNo', { length: 40 }),
  InstituteStreet: varchar('InstituteStreet', { length: 40 }).comment('Address'),
  sInstituteStreet: varchar('sInstituteStreet', { length: 40 }).comment('In Secondary Language'),
  InstituteTown: varchar('InstituteTown', { length: 40 }).comment('Address'),
  sInstituteTown: varchar('sInstituteTown', { length: 40 }).comment('In Secondary Language'),
  InstituteCountry: varchar('InstituteCountry', { length: 40 }).comment('Address'),
  InstituteTelephone1: varchar('InstituteTelephone1', { length: 15 }).comment('In Secondary Language'),
  InstituteTelephone2: varchar('InstituteTelephone2', { length: 15 }),
  InstituteTelephone3: varchar('InstituteTelephone3', { length: 15 }),
  InstituteFax: varchar('InstituteFax', { length: 15 }),
  InstituteEmail: varchar('InstituteEmail', { length: 50 }),
  InstituteWeb: varchar('InstituteWeb', { length: 50 }),
  InstituteRegistrationNo: varchar('InstituteRegistrationNo', { length: 20 }),
  InstituteRegisteredDate: date('InstituteRegisteredDate'),
  InstituteAccountsYearBeginDate: date('InstituteAccountsYearBeginDate'),
  InstituteAccountsYearEndDate: date('InstituteAccountsYearEndDate'),
  ShareValue: double('ShareValue'),
  RelatedInstituteID: varchar('RelatedInstituteID', { length: 4 }),
  sInstituteAlies: varchar('sInstituteAlies', { length: 200 }),
  eInstituteAlies: varchar('eInstituteAlies', { length: 200 }),
  SectionType: enumType('SectionType', ['BANK', 'WAREHOUSE', 'POS']).default('BANK'),
  ShotCode: varchar('ShotCode', { length: 2 }).default('-'),
  Logo: mediumblob('Logo'),
  SendSMSForEveryCustomer: int('SendSMSForEveryCustomer').default(0),
  PrintReceiptForEveryCustomer: int('PrintReceiptForEveryCustomer').default(0),
  SendOTPForEveryLogin: int('SendOTPForEveryLogin').default(0),
}, {
  charset: 'latin1',
});
