import { mysqlTable, varchar, decimal, date, enum as mysqlEnum } from 'drizzle-orm/mysql-core';

export const ledgerdetails = mysqlTable('ledgerdetails', {
  LedgerID: varchar('LedgerID', { length: 12 }).default(null),
  AccountNumber: varchar('AccountNumber', { length: 18 }).primaryKey(),
  LoanApplicationNo: varchar('LoanApplicationNo', { length: 20 }).default('-'),
  CustomerID: varchar('CustomerID', { length: 15 }).default(null),
  InterestAccount: varchar('InterestAccount', { length: 22 }).default(null),
  LoanInterestAccount: varchar('LoanInterestAccount', { length: 22 }).default(null),
  PenaltyOrReservationAccount: varchar('PenaltyOrReservationAccount', { length: 22 }).default(null),
  FundReservationPolicy: varchar('FundReservationPolicy', { length: 2 }).default('0'),
  FundAccount: varchar('FundAccount', { length: 22 }).default(null),
  FundReservationPercentage: decimal('FundReservationPercentage', { precision: 23, scale: 13 }).default('0.0000000000000'),
  FundAmount: decimal('FundAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  StationaryCharge: decimal('StationaryCharge', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DepriciationAccount: varchar('DepriciationAccount', { length: 22 }).default(null),
  DebitAmount: decimal('DebitAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  CreditAmount: decimal('CreditAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  AccountBalance: decimal('AccountBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  AccountBalanceWithInterest: decimal('AccountBalanceWithInterest', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DailyInterestMinimumBalance: decimal('DailyInterestMinimumBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  IssuedLoanAmount: decimal('IssuedLoanAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  MinimumAccountBalance: decimal('MinimumAccountBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  LowestAccountBalance: decimal('LowestAccountBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  LoanInstallment: decimal('LoanInstallment', { precision: 23, scale: 13 }).default('0.0000000000000'),
  HoldFDAccount: varchar('HoldFDAccount', { length: 18 }).default(null),
  HoldAmount: decimal('HoldAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  HoldDescription: varchar('HoldDescription', { length: 200 }).default('-'),
  Period: decimal('Period', { precision: 23, scale: 13 }).default('0.0000000000000'),
  OpenDate: date('OpenDate').default(null),
  DueDate: date('DueDate').default(null),
  AccountLastTransactionDate: date('AccountLastTransactionDate').default(null),
  AccountBeforeLastTransactionDate: date('AccountBeforeLastTransactionDate').default(null),
  LoanStartDate: date('LoanStartDate').default(null),
  LoanFreeTime: decimal('LoanFreeTime', { precision: 23, scale: 13 }).default('0.0000000000000'),
  InterestPolicy: varchar('InterestPolicy', { length: 2 }).default('00'),
  InterestRate: decimal('InterestRate', { precision: 23, scale: 13 }).default('0.0000000000000'),
  InterestAmount: decimal('InterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DueInterestAmount: decimal('DueInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ReservedInterest: decimal('ReservedInterest', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ExtraPayment: decimal('ExtraPayment', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PenaltyInterestPolicy: varchar('PenaltyInterestPolicy', { length: 2 }).default('00'),
  PaidFDInterestAmount: decimal('PaidFDInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PayableFDInterestAmount: decimal('PayableFDInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PenaltyRate: decimal('PenaltyRate', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PenaltyInterestAmount: decimal('PenaltyInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DepriciationPolicy: varchar('DepriciationPolicy', { length: 2 }).default('00'),
  DepriciationRate: varchar('DepriciationRate', { length: 6 }).default('0.000'),
  RequestedLoanAmount: decimal('RequestedLoanAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ApprovedLoanAmount: decimal('ApprovedLoanAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DailyCapitalAmount: decimal('DailyCapitalAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DailyInterestAmount: decimal('DailyInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DailyCollectionTotal: decimal('DailyCollectionTotal', { precision: 23, scale: 13 }).default('0.0000000000000'),
  JointAccountHolder1: varchar('JointAccountHolder1', { length: 9 }).default(null),
  JointAccountHolder2: varchar('JointAccountHolder2', { length: 9 }).default(null),
  JointAccountHolder3: varchar('JointAccountHolder3', { length: 9 }).default(null),
  LoanGuarantee1: varchar('LoanGuarantee1', { length: 15 }).default(null),
  LoanGuarantee2: varchar('LoanGuarantee2', { length: 15 }).default(null),
  LoanGuarantee3: varchar('LoanGuarantee3', { length: 15 }).default(null),
  LoanGuarantee4: varchar('LoanGuarantee4', { length: 15 }).default(null),
  AccountType: varchar('AccountType', { length: 2 }).default(null),
  IsDailyLoan: varchar('IsDailyLoan', { length: 1 }).default('N'),
  LoanAccountType: varchar('LoanAccountType', { length: 7 }).default(null),
  PassdueType: varchar('PassdueType', { length: 2 }).default(null),
  PassdueInstallments: decimal('PassdueInstallments', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PassdueAmount: decimal('PassdueAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  OverdueInstallment: decimal('OverdueInstallment', { precision: 23, scale: 13 }).default('0.0000000000000'),
  OverdueAmount: decimal('OverdueAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PastDuedays: decimal('PastDuedays', { precision: 23, scale: 13 }).default('0.0000000000000'),
  FDUpdateOptionID: varchar('FDUpdateOptionID', { length: 2 }).default('00'),
  Active: varchar('Active', { length: 2 }).default('Y'),
  LoanApprovalStatus: varchar('LoanApprovalStatus', { length: 50 }).default('-'),
  LoanApprovedDate: date('LoanApprovedDate').default(null),
  LoanApprovedBy: varchar('LoanApprovedBy', { length: 7 }).default(null),
  LoanRecoverACNumber: varchar('LoanRecoverACNumber', { length: 18 }).default(null),
  SelectedDayAccountBalance: decimal('SelectedDayAccountBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  AccountOpeningBalance: decimal('AccountOpeningBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PassBookType: varchar('PassBookType', { length: 2 }).default('PB'),
  PrintedRecordNo: decimal('PrintedRecordNo', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PageNo: decimal('PageNo', { precision: 23, scale: 13 }).default('0.0000000000000'),
  IssuedFDAdvanceLoanNo: varchar('IssuedFDAdvanceLoanNo', { length: 18 }).default(null),
  pawn_MarketValue: decimal('pawn_MarketValue', { precision: 23, scale: 13 }).default('0.0000000000000'),
  pawn_EstimatedAmount: decimal('pawn_EstimatedAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  pawn_PaymentAmount: decimal('pawn_PaymentAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  pawn_Reason: varchar('pawn_Reason', { length: 200 }).default(null),
  pawn_ItemTotalWeight: decimal('pawn_ItemTotalWeight', { precision: 23, scale: 13 }).default('0.0000000000000'),
  pawn_ItemGoldWeight: decimal('pawn_ItemGoldWeight', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PrintingLanguage: varchar('PrintingLanguage', { length: 2 }).default('EN'),
  IsMortgageLoan: varchar('IsMortgageLoan', { length: 1 }).default('N'),
  DeedNo: varchar('DeedNo', { length: 30 }).default('-'),
  DeedRegisteredDate: date('DeedRegisteredDate').default(null),
  DeedClosedDate: date('DeedClosedDate').default(null),
  ContractNumber: varchar('ContractNumber', { length: 100 }).default('-'),
  MortgageAmount: decimal('MortgageAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  LoanReasonID: varchar('LoanReasonID', { length: 2 }).default('0'),
  AccID: varchar('AccID', { length: 10 }).default(null),
  RJ_Old_Acc_No: varchar('RJ_Old_Acc_No', { length: 25 }).default('-'),
  NoteFirst: varchar('NoteFirst', { length: 100 }).default(null),
  NoteSecond: varchar('NoteSecond', { length: 100 }).default(null),
  AccountOpendOrLoanIssuedBy: varchar('AccountOpendOrLoanIssuedBy', { length: 7 }).default(null),
  AccountStatus: mysqlEnum('AccountStatus', ['ACTIVE', 'CLOSED', 'SUSPENDED', 'INACTIVE', 'UNCLAIMED', 'COURT DECISION', 'COURTED', 'DORMANT']).default('ACTIVE'),
  Balance_int: varchar('Balance_int', { length: 25 }).default('0.00'),
  issue_cap_int: varchar('issue_cap_int', { length: 25 }).default('0.00'),
  Ins_int: varchar('Ins_int', { length: 25 }).default('0.00'),
  issued_field_officer: varchar('issued_field_officer', { length: 2 }).default('01'),
  CollectingInstallment: decimal('CollectingInstallment', { precision: 23, scale: 13 }).default('0.0000000000000'),
  CollectedInstallments: decimal('CollectedInstallments', { precision: 23, scale: 13 }).default('0.0000000000000'),
  InstituteId: varchar('InstituteId', { length: 4 }).default(null),
  ReferenceNumber: varchar('ReferenceNumber', { length: 20 }).default(null),
  MonthlyDeductionOnInterest: decimal('MonthlyDeductionOnInterest', { precision: 23, scale: 13 }).default('0.0000000000000'),
  MaxDeductionLimit: decimal('MaxDeductionLimit', { precision: 23, scale: 13 }).default('0.0000000000000'),
  MonthlyDeduction: decimal('MonthlyDeduction', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ReceivedDeduction: decimal('ReceivedDeduction', { precision: 23, scale: 13 }).default('0.0000000000000'),
  LastMonthLoanInterest: decimal('LastMonthLoanInterest', { precision: 23, scale: 13 }).default('0.0000000000000'),
  GurTypeId: varchar('GurTypeId', { length: 3 }).default('-'),
  ReceivableCeasingCharge: decimal('ReceivableCeasingCharge', { precision: 23, scale: 13 }).default(null),
  GroupCode: varchar('GroupCode', { length: 5 }).default('-'),
  InactiveAccountNumber: varchar('InactiveAccountNumber', { length: 18 }).default(null),
  LoanReliefAllowed: varchar('LoanReliefAllowed', { length: 1 }).default('N'),
  ReliefExtendedFreeTime: decimal('ReliefExtendedFreeTime', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ReActiveDate: date('ReActiveDate').default(null),
  InactiveDate: date('InactiveDate').default(null),
  UnclaimedDate: date('UnclaimedDate').default(null),
  SentFDRenewalLetter: mysqlEnum('SentFDRenewalLetter', ['Y', 'N']).default('N'),
  FDRenewalLetterSentDate: date('FDRenewalLetterSentDate').default(null),
  DescripyionOfProprty: varchar('DescripyionOfProprty', { length: 100 }).default(null),
  VehicalModel: varchar('VehicalModel', { length: 100 }).default(null),
  ChasisNumber: varchar('ChasisNumber', { length: 100 }).default(null),
  EngineNumber: varchar('EngineNumber', { length: 100 }).default(null),
  VehicleNumber: varchar('VehicleNumber', { length: 100 }).default(null),
  vMarketValue: decimal('vMarketValue', { precision: 23, scale: 13 }).default('0.0000000000000'),
  vForcedSaleValue: decimal('vForcedSaleValue', { precision: 23, scale: 13 }).default('0.0000000000000'),
  vPayableMaxLeaseAmount: decimal('vPayableMaxLeaseAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ReliefAllowedDateBefore: date('ReliefAllowedDateBefore').default(null),
  InsuranceCompanyID: varchar('InsuranceCompanyID', { length: 2 }).default('0'),
  InsuranceStartDate: date('InsuranceStartDate').default(null),
  InsuranceRenewalDate: date('InsuranceRenewalDate').default(null),
  PreviousOrNewAccountNumber: varchar('PreviousOrNewAccountNumber', { length: 18 }).default('-'),
  ReservedInterestCopy: decimal('ReservedInterestCopy', { precision: 10, scale: 0 }).default(null),
}, {
  charset: 'latin1',
});
