import { mysqlTable, varchar, double, decimal, int, enum as mysqlEnum } from "drizzle-orm/mysql-core";

export const ledgeraccounts = mysqlTable("ledgeraccounts", {
  LedgerID: varchar("LedgerID", { length: 12 }).primaryKey(),
  LedgerName: varchar("LedgerName", { length: 100 }).default(null),
  sLedgerName: varchar("sLedgerName", { length: 100 }).default(null),
  MinimumAccountBalance: double("MinimumAccountBalance").default(null),
  LowestAccountBalance: double("LowestAccountBalance").default(null),
  InterestPolicy: varchar("InterestPolicy", { length: 2 }).default("0"),
  PenaltyPolicy: varchar("PenaltyPolicy", { length: 2 }).default("0"),
  InterestAccount: varchar("InterestAccount", { length: 22 }).default(null),
  LoanInterestAccount: varchar("LoanInterestAccount", { length: 22 }).default(null),
  PenaltyOrReservationAccount: varchar("PenaltyOrReservationAccount", { length: 22 }).default(null),
  InterestRate: varchar("InterestRate", { length: 6 }).default("0.000"),
  PenaltyRate: varchar("PenaltyRate", { length: 6 }).default("0.000"),
  DepriciationRate: varchar("DepriciationRate", { length: 6 }).default("0.000"),
  DepriciationPolicy: varchar("DepriciationPolicy", { length: 2 }).default("0"),
  DepriciationReservationAccount: varchar("DepriciationReservationAccount", { length: 22 }).default(null),
  Period: varchar("Period", { length: 4 }).default("0"),
  LoanFreeTime: varchar("LoanFreeTime", { length: 4 }).default("0"),
  FundAccount: varchar("FundAccount", { length: 22 }).default(null),
  FundReservePolicy: varchar("FundReservePolicy", { length: 2 }).default("0"),
  LoanPassduePolicy: varchar("LoanPassduePolicy", { length: 2 }).default("0"),
  InstituteID: varchar("InstituteID", { length: 4 }).default(null),
  CategoryID: varchar("CategoryID", { length: 7 }).default(null),
  YearOpeningDebit: decimal("YearOpeningDebit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  YearOpeningCredit: decimal("YearOpeningCredit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  temp_ClosingDebit: decimal("temp_ClosingDebit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  temp_ClosingCredit: decimal("temp_ClosingCredit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  EstimateOrBudget: decimal("EstimateOrBudget", { precision: 23, scale: 13 }).default("0.0000000000000"),
  RelatedLedgerID: varchar("RelatedLedgerID", { length: 12 }).default(null),
  InactiveAccountLedgerID: varchar("InactiveAccountLedgerID", { length: 12 }).default(null),
  IsInactiveAccount: varchar("IsInactiveAccount", { length: 1 }).default("N"),
  AccountStatus: varchar("AccountStatus", { length: 1 }).default("G"),
  AccountType: varchar("AccountType", { length: 3 }).default("GL"),
  LoanAccountType: mysqlEnum("LoanAccountType", ["M", "W", "D"]).default(null),
  IsTBAccount: varchar("IsTBAccount", { length: 1 }).default("Y"),
  LedgerNameAliesEN: varchar("LedgerNameAliesEN", { length: 100 }).default(null),
  LedgerNameAliesSI: varchar("LedgerNameAliesSI", { length: 100 }).default(null),
  sLedgerShortName: varchar("sLedgerShortName", { length: 100 }).default("-"),
  IsDailyLoan: varchar("IsDailyLoan", { length: 1 }).default("N"),
  cTotalBalance: decimal("cTotalBalance", { precision: 23, scale: 13 }).default("0.0000000000000"),
  cTotalCount: decimal("cTotalCount", { precision: 23, scale: 13 }).default("0.0000000000000"),
  pTotalBalance: decimal("pTotalBalance", { precision: 23, scale: 13 }).default("0.0000000000000"),
  pTotalCount: decimal("pTotalCount", { precision: 23, scale: 13 }).default("0.0000000000000"),
  dTotalBalance: decimal("dTotalBalance", { precision: 23, scale: 13 }).default("0.0000000000000"),
  dTotalCount: decimal("dTotalCount", { precision: 23, scale: 13 }).default("0.0000000000000"),
  InactiveLedgerID: varchar("InactiveLedgerID", { length: 12 }).default(null),
  UnclaimedLedgerID: varchar("UnclaimedLedgerID", { length: 12 }).default(null),
  CashFlorPDebit: decimal("CashFlorPDebit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  CashFlorPCredit: decimal("CashFlorPCredit", { precision: 23, scale: 13 }).default("0.0000000000000"),
  FundReservationPercentage: decimal("FundReservationPercentage", { precision: 23, scale: 13 }).default("0.0000000000000"),
  ClosingStockActive: decimal("ClosingStockActive", { precision: 23, scale: 13 }).default("0.0000000000000"),
  OpeningStockActive: decimal("OpeningStockActive", { precision: 23, scale: 13 }).default("0.0000000000000"),
  IsWHTAllowed: mysqlEnum("IsWHTAllowed", ["Y", "N"]).default("Y"),
  PastdueLetterType: mysqlEnum("PastdueLetterType", ["1", "2"]).default("2"),
  LET_1ST_PASTDUE_REMINDER_DAYS: double("LET_1ST_PASTDUE_REMINDER_DAYS").default("30"),
  LET_2ND_PASTDUE_REMINDER_DAYS: double("LET_2ND_PASTDUE_REMINDER_DAYS").default("60"),
  LET_3RD_PASTDUE_REMINDER_DAYS: double("LET_3RD_PASTDUE_REMINDER_DAYS").default("90"),
  LET_4TH_PASTDUE_REMINDER_DAYS: double("LET_4TH_PASTDUE_REMINDER_DAYS").default("0"),
  LET_5TH_PASTDUE_REMINDER_DAYS: double("LET_5TH_PASTDUE_REMINDER_DAYS").default("0"),
  LET_LETTER_OF_DEMAND_DAYS: double("LET_LETTER_OF_DEMAND_DAYS").default("120"),
  LET_1ST_PASTDUE_REMINDER_INS: double("LET_1ST_PASTDUE_REMINDER_INS").default("1"),
  LET_2ND_PASTDUE_REMINDER_INS: double("LET_2ND_PASTDUE_REMINDER_INS").default("2"),
  LET_3RD_PASTDUE_REMINDER_INS: double("LET_3RD_PASTDUE_REMINDER_INS").default("3"),
  LET_4TH_PASTDUE_REMINDER_INS: double("LET_4TH_PASTDUE_REMINDER_INS").default("0"),
  LET_5TH_PASTDUE_REMINDER_INS: double("LET_5TH_PASTDUE_REMINDER_INS").default("0"),
  LET_LETTER_OF_DEMAND_INS: double("LET_LETTER_OF_DEMAND_INS").default("4"),
});
