import { mysqlTable, varchar, int, decimal, date, time, enum as mysqlEnum } from 'drizzle-orm/mysql-core';

export const ledgertransactions = mysqlTable('ledgertransactions', {
  ID: int('ID').primaryKey().autoIncrement(),
  TransactionID: varchar('TransactionID', { length: 14 }),
  LedgerID: varchar('LedgerID', { length: 12 }),
  CashOrBankLedgerID: varchar('CashOrBankLedgerID', { length: 12 }).default('(NULL)'),
  AccountNumber: varchar('AccountNumber', { length: 20 }).default(null),
  CustomerID: varchar('CustomerID', { length: 9 }).default(null),
  CustomerName: varchar('CustomerName', { length: 350 }).default('-'),
  sCustomerName: varchar('sCustomerName', { length: 300 }).default('-'),
  CustomerAddress: varchar('CustomerAddress', { length: 200 }).default('-'),
  sCustomerAddress: varchar('sCustomerAddress', { length: 200 }).default('-'),
  TransactionDate: date('TransactionDate').default(null),
  TransactionTime: varchar('TransactionTime', { length: 20 }).default(null),
  ScheduledDate: date('ScheduledDate').default(null),
  DebitAmount: decimal('DebitAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  CreditAmount: decimal('CreditAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  AccountBalance: decimal('AccountBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  AccountBalanceWithInterest: decimal('AccountBalanceWithInterest', { precision: 23, scale: 13 }).default(null),
  InterestRate: decimal('InterestRate', { precision: 23, scale: 13 }).default('0.0000000000000'),
  InterestAmount: decimal('InterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DueInterestAmount: decimal('DueInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  PenaltyInterestAmount: decimal('PenaltyInterestAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  FundAmount: decimal('FundAmount', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ExtraPayment: decimal('ExtraPayment', { precision: 23, scale: 13 }).default('0.0000000000000'),
  ChequeNo: varchar('ChequeNo', { length: 20 }).default('-'),
  ChequeDate: date('ChequeDate').default(null),
  Description: varchar('Description', { length: 250 }).default('-'),
  sDescription: varchar('sDescription', { length: 250 }).default('-'),
  prntDescription: varchar('prntDescription', { length: 250 }).default('-'),
  TransactionType: varchar('TransactionType', { length: 2 }).default(null),
  TransactionLog: varchar('TransactionLog', { length: 20 }).default('-'),
  TransactionNo: int('TransactionNo').default('0'),
  PageNo: int('PageNo').default('0'),
  UserID: varchar('UserID', { length: 2 }).default(null),
  TransactionValidate: varchar('TransactionValidate', { length: 1 }).default('Y'),
  TransactionValidatePrv: varchar('TransactionValidatePrv', { length: 1 }).default('Y'),
  PrintStatus: varchar('PrintStatus', { length: 1 }).default('N'),
  TransactionRelatedBranch: varchar('TransactionRelatedBranch', { length: 2 }).default(null),
  OLd_transactionLog: varchar('OLd_transactionLog', { length: 100 }).default(null),
  CashOrCurrentAccount: mysqlEnum('CashOrCurrentAccount', ['CA', 'CU', 'JR', '-']).default('-'),
  CashTenderd: decimal('CashTenderd', { precision: 23, scale: 13 }).default('0.0000000000000'),
  CashBalance: decimal('CashBalance', { precision: 23, scale: 13 }).default('0.0000000000000'),
  DebitReverse: decimal('DebitReverse', { precision: 23, scale: 13 }).default('0.0000000000000'),
  CreditReverse: decimal('CreditReverse', { precision: 23, scale: 13 }).default('0.0000000000000'),
  IsTransactionUndone: varchar('IsTransactionUndone', { length: 1 }).default('0'),
  TaxAmount: decimal('TaxAmount', { precision: 23, scale: 13 }).default(null),
  IssuedTime: time('IssuedTime').default(null),
  TransactionEntryType: varchar('TransactionEntryType', { length: 1 }).default('A'),
  TransactionForm: varchar('TransactionForm', { length: 50 }).default('-'),
}, {
  charset: 'latin1',
});
